# Generated by Django 2.0.3 on 2018-03-18 23:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=30)),
                ('playersSessionKeys', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=2)),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Game')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
