# Generated by Django 2.0.3 on 2018-03-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20180319_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='playersSessionKeys',
        ),
    ]
