# Generated by Django 2.0.3 on 2018-03-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_room_playerssessionkeys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='game',
        ),
        migrations.RemoveField(
            model_name='room',
            name='password',
        ),
    ]
