# Generated by Django 2.0.3 on 2018-03-20 15:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessboard',
            name='fields',
        ),
        migrations.AddField(
            model_name='fieldwithchesspiece',
            name='chessBoard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.ChessBoard'),
        ),
        migrations.AlterField(
            model_name='fieldwithchesspiece',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.AbstractField'),
        ),
        migrations.AlterField(
            model_name='game',
            name='points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0, null=True), size=2),
        ),
    ]
