# Generated by Django 2.0.3 on 2018-03-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20180320_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='points',
        ),
        migrations.AddField(
            model_name='game',
            name='black_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.CharField(choices=[('w', 'White Player'), ('b', 'Black Player')], default='w', max_length=15),
        ),
        migrations.AddField(
            model_name='game',
            name='white_points',
            field=models.IntegerField(default=0),
        ),
    ]
