# Generated by Django 2.0.3 on 2018-03-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20180325_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbstractField',
        ),
        migrations.RemoveField(
            model_name='fieldwithchesspiece',
            name='field',
        ),
    ]
