# Generated by Django 2.0.3 on 2018-05-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20180325_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_player_socket_name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='white_player_socket_name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
